#!/bin/bash

browserify main.js --s MyModule -o bundle.js
echo "updating git-upload-pack commands"
default="\'multi_ack_detailed\',"
updated="$default\'filter=blob:none\',\'thin-pack\',"
sed -i -e "s/$default/$updated/g" bundle.js
cp bundle.js chrome/includes/
#rm -rf upload
#cp -rf chrome upload
#rm -rf native-git.zip
#cd upload
#zip -r ../native-git.zip *
#cd ..
#rm -rf upload
